//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerTransitioningDelegate.h"
#import "VideoPlayerDelegate.h"

@class AVPlayerViewController, CancelOnTouchView, NSString, UIColor, VideoPlayer;

@interface AVKitVideoPlayback : NSObject <VideoPlayerDelegate, UIViewControllerTransitioningDelegate>
{
    AVPlayerViewController *videoViewController;
    VideoPlayer *videoPlayer;
    CancelOnTouchView *cancelOnTouchView;
    UIColor *bgColor;
    NSString *videoGravity;
    _Bool showControls;
    _Bool cancelOnTouch;
}

+ (void)InitClass;
+ (_Bool)IsSupported;
- (void).cxx_destruct;
- (void)actuallyStartTheMovie:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (void)dealloc;
- (void)finish;
- (void)handleTap:(id)arg1;
- (id)initAndPlay:(id)arg1 bgColor:(id)arg2 showControls:(_Bool)arg3 videoGravity:(id)arg4 cancelOnTouch:(_Bool)arg5;
- (void)onPlayerDidFinishPlayingVideo;
- (void)onPlayerError:(id)arg1;
- (void)onPlayerReady;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

