//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CRAppLocator : NSObject
{
    NSString *_apiURL;
    NSString *_apmURL;
    NSString *_appLoadURL;
    NSString *_txnURL;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *apiURL; // @synthesize apiURL=_apiURL;
@property(readonly, copy, nonatomic) NSString *apmURL; // @synthesize apmURL=_apmURL;
@property(readonly, copy, nonatomic) NSString *appLoadURL; // @synthesize appLoadURL=_appLoadURL;
- (id)getDomainFromAppId:(id)arg1;
- (id)initWithAppId:(id)arg1;
@property(readonly, copy, nonatomic) NSString *txnURL; // @synthesize txnURL=_txnURL;

@end

