//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CRDirectoryTree, NSFileHandle, NSMutableArray, NSString;

@interface CRBreadcrumbsArchive : NSObject
{
    unsigned int _maxCount;
    NSMutableArray *_breadcrumbs;
    NSMutableArray *_reservedBreadcrumbs;
    CRDirectoryTree *_directoryTree;
    NSString *_nameDirectory;
    NSFileHandle *_fileHandle;
    NSFileHandle *_reservedFileHandle;
    NSString *_path0;
    NSString *_path1;
    NSString *_pathToReservedBreadcrumbs;
    unsigned long long _breadcrumbCount;
    unsigned long long _countOnActiveFile;
}

+ (id)convertArrayToUserBreadcrumbFormat:(id)arg1;
- (void).cxx_destruct;
- (void)addBreadcrumb:(int)arg1 withObject:(id)arg2;
- (void)addBreadcrumb:(int)arg1 withObject:(id)arg2 withTimestamp:(id)arg3;
- (void)addBreadcrumbOpenFile:(id)arg1;
- (void)addBreadcrumbShuffleFiles;
- (void)addBreadcrumbToArray:(id)arg1;
- (void)addBreadcrumbToFile:(id)arg1;
- (void)addSessionStartBreadcrumb;
@property(nonatomic) unsigned long long breadcrumbCount; // @synthesize breadcrumbCount=_breadcrumbCount;
@property(retain, nonatomic) NSMutableArray *breadcrumbs; // @synthesize breadcrumbs=_breadcrumbs;
- (void)clearAndAddBreadcrumbToReservedArray:(id)arg1;
- (void)clearAndAddBreadcrumbToReservedFile:(id)arg1;
- (void)clearBreadcrumbs;
- (void)clearBreadcrumbsOnDisk;
@property(nonatomic) unsigned long long countOnActiveFile; // @synthesize countOnActiveFile=_countOnActiveFile;
@property(nonatomic) __weak CRDirectoryTree *directoryTree; // @synthesize directoryTree=_directoryTree;
- (id)extractRecentUserBreadcrumbs;
@property(retain) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
- (id)initWithName:(id)arg1 maxCount:(unsigned int)arg2;
- (_Bool)isPlausibleBreadcrumb:(id)arg1;
@property(nonatomic) unsigned int maxCount; // @synthesize maxCount=_maxCount;
@property(copy, nonatomic) NSString *nameDirectory; // @synthesize nameDirectory=_nameDirectory;
@property(copy, nonatomic) NSString *path0; // @synthesize path0=_path0;
- (unsigned long long)path0FileSize;
@property(copy, nonatomic) NSString *path1; // @synthesize path1=_path1;
- (unsigned long long)path1FileSize;
@property(copy, nonatomic) NSString *pathToReservedBreadcrumbs; // @synthesize pathToReservedBreadcrumbs=_pathToReservedBreadcrumbs;
- (id)readBreadcrumbs;
- (void)readBreadcrumbsFromFile:(id)arg1 intoArray:(id)arg2;
- (id)recentBreadcrumbs;
@property(retain, nonatomic) NSMutableArray *reservedBreadcrumbs; // @synthesize reservedBreadcrumbs=_reservedBreadcrumbs;
@property(retain) NSFileHandle *reservedFileHandle; // @synthesize reservedFileHandle=_reservedFileHandle;
- (void)saveBreadcrumbs;

@end

