//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CritterImpl, NSMutableData, NSURLResponse;

@interface CRConnectionHandler : NSObject
{
    CritterImpl *_delegate;
    NSMutableData *_dataReceived;
    NSURLResponse *_response;
}

+ (id)handlerWithDelegate:(id)arg1;
- (void).cxx_destruct;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
@property(retain) NSMutableData *dataReceived; // @synthesize dataReceived=_dataReceived;
- (id)dataReceivedAsString;
@property(readonly) CritterImpl *delegate; // @synthesize delegate=_delegate;
- (void)doSendRequest:(id)arg1;
- (void)handleError:(id)arg1;
- (void)handleResponse:(long long)arg1 andData:(id)arg2;
- (id)init;
- (id)initWithCritterDelegate:(id)arg1;
- (_Bool)receivedErrorResponse;
@property(retain) NSURLResponse *response; // @synthesize response=_response;
- (void)sendRequest:(id)arg1;
- (long long)statusCode;

@end

