//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CRPreferences, CRReachability, CritterImpl, NSMutableSet, NSOperationQueue, NSString;

@interface CRCrashArchive : NSObject
{
    unsigned long long _maxSavedCrashReports;
    NSString *_baseCritterURL;
    NSString *_crashDirectory;
    NSMutableSet *_reportsInSendQueue;
    CRReachability *_reachability;
    CritterImpl *_critterImpl;
    NSOperationQueue *_sendQueue;
    CRPreferences *_storedState;
}

+ (id)crashReportDirectory;
- (void).cxx_destruct;
@property(retain) NSString *baseCritterURL; // @synthesize baseCritterURL=_baseCritterURL;
@property(retain) NSString *crashDirectory; // @synthesize crashDirectory=_crashDirectory;
@property __weak CritterImpl *critterImpl; // @synthesize critterImpl=_critterImpl;
- (void)dealloc;
- (void)deleteAllCrashReports;
- (void)deleteCrashReport:(id)arg1;
- (id)init;
- (id)initWithCritterImpl:(id)arg1 andStoredState:(id)arg2 andBaseURL:(id)arg3;
- (_Bool)loadCrashInfoFromPath:(id)arg1 crashInfo:(id *)arg2 rawCrashData:(id *)arg3;
- (id)makeCrashDataName;
- (id)makeCrashInfoNameFor:(id)arg1;
@property(nonatomic) unsigned long long maxOfflineCrashReports; // @synthesize maxOfflineCrashReports=_maxSavedCrashReports;
- (void)notifySendReportFailed:(id)arg1;
- (id)pendingCrashReports;
@property(retain) CRReachability *reachability; // @synthesize reachability=_reachability;
- (void)reachabilityChanged:(id)arg1;
- (void)registerForOnlineCallbacks;
@property(retain) NSMutableSet *reportsInSendQueue; // @synthesize reportsInSendQueue=_reportsInSendQueue;
- (id)saveCrashInfo:(id)arg1 andRawCrashData:(id)arg2;
- (_Bool)sendCrashReport:(id)arg1 withError:(id *)arg2;
- (void)sendCrashReports;
@property(retain) NSOperationQueue *sendQueue; // @synthesize sendQueue=_sendQueue;
@property(retain) CRPreferences *storedState; // @synthesize storedState=_storedState;

@end

