//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CRDevice : NSObject
{
    NSMutableDictionary *_deviceInfo;
}

+ (id)deviceFromCurrentDevice;
+ (id)deviceFromPersistentState:(id)arg1;
+ (id)deviceWithDummyInfo;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)batteryLevel;
- (id)carrier;
- (id)description;
@property(copy, nonatomic) NSMutableDictionary *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
- (void)flushToPersistentState:(id)arg1;
- (id)freeDiskSpace;
- (id)initFromCurrentDevice;
- (id)initFromDeviceInfoDictionary:(id)arg1;
- (id)initFromPersistentState:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)locale;
- (id)memoryUsage;
- (id)mobileCountryCode;
- (id)mobileNetworkCode;
- (id)model;
- (id)platform;
- (id)systemName;
- (id)systemVersion;
- (void)updateOrientation;

@end

