//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CRDirectoryTree : NSObject
{
    NSString *_rootDirectory;
    NSString *_beginDirectory;
    NSString *_normalDirectory;
    NSString *_sendDirectory;
    NSString *_sentDirectory;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)absolutePath:(id)arg1;
@property(readonly, nonatomic) NSString *beginDirectory; // @synthesize beginDirectory=_beginDirectory;
- (id)createDirectory:(id)arg1;
- (id)createRootDirectory;
- (id)init;
- (void)initFileSystem;
- (_Bool)moveItemAtPath:(id)arg1 toPath:(id)arg2;
- (void)moveItemsFrom:(id)arg1 toDirectory:(id)arg2;
@property(readonly, nonatomic) NSString *normalDirectory; // @synthesize normalDirectory=_normalDirectory;
- (_Bool)removeItemAtPath:(id)arg1;
- (void)reset;
- (void)resetDirectory:(id)arg1;
@property(readonly, nonatomic) NSString *rootDirectory; // @synthesize rootDirectory=_rootDirectory;
@property(readonly, nonatomic) NSString *sendDirectory; // @synthesize sendDirectory=_sendDirectory;
@property(readonly, nonatomic) NSString *sentDirectory; // @synthesize sentDirectory=_sentDirectory;

@end

