//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface CrittercismConfig : NSObject
{
    _Bool _monitorNSURLConnection;
    _Bool _monitorNSURLSession;
    _Bool _monitorUIWebView;
    _Bool _monitorWKWebView;
    _Bool _monitorWCSession;
    _Bool _enableServiceMonitoring;
    _Bool _delaySendingAppLoad;
    long long _loggingLevel;
    NSArray *_urlFilters;
    id <CrittercismDelegate> _delegate;
}

+ (id)defaultConfig;
- (void).cxx_destruct;
@property(nonatomic) _Bool delaySendingAppLoad; // @synthesize delaySendingAppLoad=_delaySendingAppLoad;
@property(retain, nonatomic) id <CrittercismDelegate> delegate; // @synthesize delegate=_delegate;
- (id)description;
@property(nonatomic) _Bool enableServiceMonitoring; // @synthesize enableServiceMonitoring=_enableServiceMonitoring;
- (id)init;
- (long long)internalLoggingLevel;
@property(nonatomic) long long loggingLevel; // @synthesize loggingLevel=_loggingLevel;
@property(nonatomic) _Bool monitorNSURLConnection; // @synthesize monitorNSURLConnection=_monitorNSURLConnection;
@property(nonatomic) _Bool monitorNSURLSession; // @synthesize monitorNSURLSession=_monitorNSURLSession;
@property(nonatomic) _Bool monitorUIWebView; // @synthesize monitorUIWebView=_monitorUIWebView;
@property(nonatomic) _Bool monitorWCSession; // @synthesize monitorWCSession=_monitorWCSession;
@property(nonatomic) _Bool monitorWKWebView; // @synthesize monitorWKWebView=_monitorWKWebView;
@property(retain, nonatomic) NSArray *urlFilters; // @synthesize urlFilters=_urlFilters;

@end

