//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSUserDefaults;

@interface CRLegacyDeviceIdFinder : NSObject
{
    NSString *_appId;
    NSUserDefaults *_defaults;
}

+ (id)idFinderUsingAppId:(id)arg1 andUserDefaults:(id)arg2;
- (void).cxx_destruct;
@property(retain) NSString *appId; // @synthesize appId=_appId;
@property(retain) NSUserDefaults *defaults; // @synthesize defaults=_defaults;
- (id)getDeviceUUIDFromAppSettings;
- (id)getDeviceUUIDFromPasteboards;
- (id)initWithAppId:(id)arg1 andUserDefaults:(id)arg2;
- (id)lookupId;

@end

