//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class CRNetStatDispatch, CRRequestState, NSString;

@interface CRNSURLConnectionDelegateProxy : NSProxy <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    id _delegate;
    CRNetStatDispatch *_dispatch;
    CRRequestState *_reqState;
}

+ (void)instrumentNSURLConnectionWithDispatch:(id)arg1;
+ (_Bool)isInstrumented;
+ (void)uninstrumentNSURLConnection;
- (void).cxx_destruct;
- (void)addAssociationToConnection:(id)arg1;
- (_Bool)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)connection:(id)arg1 didWriteData:(long long)arg2 totalBytesWritten:(long long)arg3 expectedTotalBytes:(long long)arg4;
- (id)connection:(id)arg1 needNewBodyStream:(id)arg2;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connectionDidFinishDownloading:(id)arg1 destinationURL:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connectionDidResumeDownloading:(id)arg1 totalBytesWritten:(long long)arg2 expectedTotalBytes:(long long)arg3;
- (_Bool)connectionShouldUseCredentialStorage:(id)arg1;
@property(retain, nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CRNetStatDispatch *dispatch; // @synthesize dispatch=_dispatch;
- (void)forwardInvocation:(id)arg1;
- (id)initWithDelegate:(id)arg1 andStatsDispatch:(id)arg2;
- (void)logStats;
- (id)methodSignatureForSelector:(SEL)arg1;
@property(retain, nonatomic) CRRequestState *reqState; // @synthesize reqState=_reqState;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)startRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

