//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@class CRNetStatDispatch, CRRequestState, NSURLSessionTask;

@interface CRNSURLSessionTaskProxy : NSProxy
{
    NSURLSessionTask *_taskDelegate;
    CRNetStatDispatch *_dispatch;
    CRRequestState *_reqState;
    unsigned long long _resumeDataSize;
}

- (void).cxx_destruct;
- (void)cancel;
- (id)debugDescription;
- (id)description;
@property(readonly, nonatomic) CRNetStatDispatch *dispatch; // @synthesize dispatch=_dispatch;
- (void)finishedDownloadingToURL:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)initDataTaskWithSession:(id)arg1 URL:(id)arg2 completionHandler:(id)arg3 dispatch:(id)arg4;
- (id)initDataTaskWithSession:(id)arg1 request:(id)arg2 completionHandler:(id)arg3 dispatch:(id)arg4;
- (id)initDownloadTaskWithSession:(id)arg1 request:(id)arg2 completionHandler:(id)arg3 dispatch:(id)arg4;
- (id)initDownloadTaskWithSession:(id)arg1 resumeData:(id)arg2 completionHandler:(id)arg3 dispatch:(id)arg4;
- (id)initDownloadTaskWithSession:(id)arg1 url:(id)arg2 completionHandler:(id)arg3 dispatch:(id)arg4;
- (id)initWithTaskDelegate:(id)arg1 dispatch:(id)arg2;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)receivedBytes:(unsigned long long)arg1;
- (void)receivedResponse:(id)arg1;
@property(retain, nonatomic) CRRequestState *reqState; // @synthesize reqState=_reqState;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)responseFinishedWithError:(id)arg1;
- (void)resume;
@property(nonatomic) unsigned long long resumeDataSize; // @synthesize resumeDataSize=_resumeDataSize;
- (void)suspend;
@property(readonly, nonatomic) NSURLSessionTask *taskDelegate; // @synthesize taskDelegate=_taskDelegate;
- (id)wrapDataCompletionHandler:(id)arg1 forSession:(id)arg2;
- (id)wrapDownloadCompletionHandler:(id)arg1 forSession:(id)arg2;

@end

