//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CRReachability : NSObject
{
    _Bool localWiFiRef;
    _Bool _scheduled;
    struct __SCNetworkReachability *_reachabilityRef;
    NSString *_notificationCenterKey;
}

+ (id)reachabilityForHostName:(id)arg1;
+ (id)reachabilityForHostName:(id)arg1 withNotificationKey:(id)arg2;
+ (id)reachabilityForInternetConnection;
+ (id)reachabilityForWiFi;
+ (id)reachabilityForWiFiWithNotificationKey:(id)arg1;
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)arg1 withKey:(id)arg2;
- (void).cxx_destruct;
- (_Bool)connectionRequired;
- (int)currentReachabilityStatus;
- (id)currentReachabilityStatusString;
- (void)dealloc;
- (id)initWithNotificationKey:(id)arg1;
@property(retain) NSString *notificationCenterKey; // @synthesize notificationCenterKey=_notificationCenterKey;
- (_Bool)startNotifier;
- (void)stopNotifier;

@end

