//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CRDirectoryTree, CRSequenceNumber, NSDictionary, NSMutableDictionary, NSString;

@interface CRTransactionReporter : NSObject
{
    struct dispatch_queue_s *queue;
    struct dispatch_group_s *group;
    _Bool canResume;
    int finishedCount;
    _Bool batching;
    _Bool _isForegrounded;
    _Bool _isLoaded;
    _Bool _shuttingdown;
    int _transactionCounter;
    NSDictionary *_appState;
    double _defaultTimeout;
    NSDictionary *_thresholds;
    CRDirectoryTree *_directoryTree;
    CRSequenceNumber *_normalCounter;
    NSMutableDictionary *_transactionsDictionary;
    double _endTime;
    NSString *_cr_endTimeString;
    double _interval;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addTransaction:(id)arg1;
- (id)allTransactions;
@property(retain, nonatomic) NSDictionary *appState; // @synthesize appState=_appState;
- (void)autoTransaction:(id)arg1 withBeginTime:(double)arg2 withEndTime:(double)arg3;
- (void)background;
- (void)backgrounded;
- (void)cancelTransaction:(id)arg1;
@property(copy, nonatomic) NSString *cr_endTimeString; // @synthesize cr_endTimeString=_cr_endTimeString;
- (void)cr_setEndTime:(double)arg1;
- (id)crashTransactionsOnPluginException;
- (id)crashedJSONFrom:(id)arg1;
- (id)crashedTransactions:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) double defaultTimeout; // @synthesize defaultTimeout=_defaultTimeout;
@property(nonatomic) CRDirectoryTree *directoryTree; // @synthesize directoryTree=_directoryTree;
- (void)disableSampling;
- (void)enableSamplingWithFrequency:(id)arg1 withDefaultTimeout:(double)arg2 withThresholds:(id)arg3;
@property(readonly, nonatomic) double endTime; // @synthesize endTime=_endTime;
- (void)foreground;
- (void)foregroundBackgroundCheck:(id)arg1;
- (void)foregrounded;
- (void)handleNotification:(id)arg1;
- (id)init;
- (void)initConfiguration;
- (void)initCounters;
- (void)initNotifications;
- (void)initQueue;
@property(nonatomic) double interval; // @synthesize interval=_interval;
@property(readonly, nonatomic) _Bool isForegrounded; // @synthesize isForegrounded=_isForegrounded;
@property(nonatomic) _Bool isLoaded; // @synthesize isLoaded=_isLoaded;
- (void)load;
- (void)move:(id)arg1 fromDirectory:(id)arg2 toDirectory:(id)arg3;
- (int)newTransactionId;
- (void)normalBatch;
- (void)normalBatchBarrier;
@property(retain, nonatomic) CRSequenceNumber *normalCounter; // @synthesize normalCounter=_normalCounter;
- (void)normalDelivery;
- (id)normalJSONFrom:(id)arg1;
- (void)normalReport;
- (double)normalReportBeginTimeFor:(id)arg1;
- (double)normalReportEndTimeFor:(id)arg1;
- (id)normalReportTransactions;
- (void)normalWork;
- (_Bool)normalWorkInNormalDirectoryToDo;
- (_Bool)normalWorkToDo;
- (id)path:(id)arg1;
- (id)path:(id)arg1 forDirectory:(id)arg2;
- (void)remove:(id)arg1 fromDirectory:(id)arg2;
- (void)reset;
- (void)resume;
- (void)resumeFirstTime;
- (void)save:(id)arg1;
@property(nonatomic) _Bool shuttingdown; // @synthesize shuttingdown=_shuttingdown;
@property(nonatomic) int transactionCounter; // @synthesize transactionCounter=_transactionCounter;
@property(retain, nonatomic) NSMutableDictionary *transactionsDictionary; // @synthesize transactionsDictionary=_transactionsDictionary;
@property(readonly, nonatomic) NSDictionary *thresholds; // @synthesize thresholds=_thresholds;
- (unsigned long long)transactionCount;
- (id)transactionForId:(int)arg1;
- (id)transactionForName:(id)arg1;

@end

