//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CRDirectoryTree, NSString;

@interface CRTransactionSender : NSObject
{
    struct dispatch_queue_s *queue;
    _Bool canResume;
    _Bool _enabled;
    _Bool _isLoaded;
    _Bool _isReachable;
    NSString *_critterTxnURL;
    CRDirectoryTree *_directoryTree;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *critterTxnURL; // @synthesize critterTxnURL=_critterTxnURL;
@property(nonatomic) CRDirectoryTree *directoryTree; // @synthesize directoryTree=_directoryTree;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (void)handleNotification:(id)arg1;
- (id)init;
- (void)initConfiguration;
- (void)initNotifications;
- (void)initQueue;
- (void)initTxnURL;
@property(nonatomic) _Bool isLoaded; // @synthesize isLoaded=_isLoaded;
@property(nonatomic) _Bool isReachable; // @synthesize isReachable=_isReachable;
- (void)normalDelivery;
- (_Bool)normalWorkToDo;
- (void)resume;
- (void)resumeFirstTime;
- (void)sendDidFinish:(id)arg1;
- (void)sendReport:(id)arg1;
- (void)sendReportOnMainThread:(id)arg1;

@end

