//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DisplayConnection, NSMapTable;

@interface DisplayManager : NSObject
{
    NSMapTable *_displayConnection;
    DisplayConnection *_mainDisplay;
    unsigned long long displayCount;
}

+ (void)Initialize;
+ (id)Instance;
- (void).cxx_destruct;
- (id)display:(id)arg1;
- (_Bool)displayAvailable:(id)arg1;
@property(readonly, nonatomic) unsigned long long displayCount; // @synthesize displayCount;
- (void)endFrameRendering;
- (void)enumerateDisplaysWithBlock:(id)arg1;
- (id)init;
@property(readonly, nonatomic) DisplayConnection *mainDisplay; // @synthesize mainDisplay=_mainDisplay;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)present;
- (void)registerScreen:(id)arg1;
- (void)screenDidConnect:(id)arg1;
- (void)screenDidDisconnect:(id)arg1;
- (void)startFrameRendering;
- (void)updateDisplayListInUnity;

@end

