//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface GIDRuntimeConfigFetcher : NSObject
{
    NSString *_version;
    NSString *_query;
    NSMutableArray *_handlers;
}

+ (id)serverURLPrefix;
+ (void)setServerURLPrefix:(id)arg1;
- (void).cxx_destruct;
- (void)fetchWithCompletionHandler:(id)arg1;
- (void)fetchWithURLString:(id)arg1 history:(id)arg2;
- (id)initWithSDKVersion:(id)arg1 clientID:(id)arg2 bundleID:(id)arg3;

@end

