//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GIDAppSwitchConfig, NSString;

@interface GIDRuntimeConfig : NSObject
{
    GIDAppSwitchConfig *_appSwitch;
    NSString *_developerMessage;
    NSString *_redirectURLString;
}

+ (id)defaultConfig;
- (void).cxx_destruct;
@property(readonly, nonatomic) GIDAppSwitchConfig *appSwitch; // @synthesize appSwitch=_appSwitch;
@property(readonly, nonatomic) NSString *developerMessage; // @synthesize developerMessage=_developerMessage;
- (id)initWithDictionary:(id)arg1;
@property(readonly, nonatomic) NSString *redirectURLString; // @synthesize redirectURLString=_redirectURLString;

@end

