//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "GIDSignInWebViewDelegate.h"

@class NSError, NSString, NSURL;

@interface GIDSignInWebViewController : UIViewController <GIDSignInWebViewDelegate>
{
    NSURL *_pendingURL;
    NSError *_pendingError;
    _Bool _shouldKeepLSOCookies;
    _Bool _didDispatchToIOL;
    NSURL *_URL;
    id <GIDSignInWebViewControllerDelegate> _delegate;
}

+ (void)purgeCookieCache;
- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void)cancel;
- (void)completeWithURL:(id)arg1 error:(id)arg2;
@property(nonatomic) __weak id <GIDSignInWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endProtectedCookieSectionKeepingLSOCookies:(_Bool)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;
- (void)loadView;
- (void)signInWebView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)signInWebView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)startProtectedCookieSection;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

