//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView;

@interface GIDSignInButton : UIControl
{
    UIImageView *_icon;
    long long _style;
    long long _colorScheme;
    unsigned long long _brand;
    unsigned long long _buttonState;
}

+ (id)buttonTextFont;
+ (struct CGSize)textSize:(id)arg1 withFont:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long brand; // @synthesize brand=_brand;
- (unsigned long long)brandFromScopes:(id)arg1;
@property(nonatomic) unsigned long long buttonState; // @synthesize buttonState=_buttonState;
- (id)buttonText;
@property(nonatomic) long long colorScheme; // @synthesize colorScheme=_colorScheme;
- (void)dealloc;
- (void)drawButtonBackground:(struct CGContext *)arg1;
- (void)drawButtonText:(struct CGContext *)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isConstraint:(id)arg1 equalToConstraint:(id)arg2;
- (void)loadIcon;
- (double)minWidth;
- (void)pressed;
- (void)scopesDidChange:(id)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void)sharedInit;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)switchToDisabled;
- (void)switchToNormal;
- (void)switchToPressed;
- (void)updateConstraints;
- (void)updateUI;

@end

