//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"

@class GSDK_GTMSessionFetcherService, NSMutableDictionary, NSObject<OS_dispatch_semaphore>, NSString, NSTimer, NSURLSession;

@interface GSDK_GTMSessionFetcherSessionDelegateDispatcher : NSObject <NSURLSessionDelegate>
{
    GSDK_GTMSessionFetcherService *_parentService;
    NSURLSession *_session;
    NSObject<OS_dispatch_semaphore> *_sessionCreationSemaphore;
    NSMutableDictionary *_taskToFetcherMap;
    NSTimer *_discardTimer;
    double _discardInterval;
}

- (void).cxx_destruct;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didBecomeDownloadTask:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(id)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 willCacheResponse:(id)arg3 completionHandler:(id)arg4;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didResumeAtOffset:(long long)arg3 expectedTotalBytes:(long long)arg4;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(id)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 needNewBodyStream:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(id)arg5;
- (void)abandon;
@property(readonly, copy) NSString *description;
- (void)destroyDiscardTimer;
- (void)destroySessionAndTimer;
@property double discardInterval;
- (void)discardTimerFired:(id)arg1;
- (id)fetcherForTask:(id)arg1;
- (id)init;
- (id)initWithParentService:(id)arg1 sessionDiscardInterval:(double)arg2;
- (void)removeFetcher:(id)arg1;
- (void)removeTaskFromMap:(id)arg1;
@property(retain) NSURLSession *session;
@property(readonly) NSObject<OS_dispatch_semaphore> *sessionCreationSemaphore; // @synthesize sessionCreationSemaphore=_sessionCreationSemaphore;
- (void)setFetcher:(id)arg1 forTask:(id)arg2;
- (void)startDiscardTimer;
- (void)startSessionUsage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

