//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSDK_GTMSessionFetcher.h"

@interface GSDK_GTMSessionFetcher (GTMSessionFetcherLogging)
+ (void)deleteLogDirectoriesOlderThanDate:(id)arg1;
+ (id)htmlFileName;
+ (_Bool)isLoggingEnabled;
+ (_Bool)isLoggingToFileEnabled;
+ (id)logDirectoryForCurrentRun;
+ (id)loggingDateStamp;
+ (id)loggingDirectory;
+ (id)loggingProcessName;
+ (id)processNameLogPrefix;
+ (void)setLogDirectoryForCurrentRun:(id)arg1;
+ (void)setLoggingDateStamp:(id)arg1;
+ (void)setLoggingDirectory:(id)arg1;
+ (void)setLoggingEnabled:(_Bool)arg1;
+ (void)setLoggingProcessName:(id)arg1;
+ (void)setLoggingToFileEnabled:(_Bool)arg1;
+ (id)symlinkNameSuffix;
- (id)formattedStringFromData:(id)arg1 contentType:(id)arg2 JSON:(id *)arg3;
- (void)logFetchWithError:(id)arg1;
- (id)loggedInputStreamForInputStream:(id)arg1;
- (id)loggedStreamProviderForStreamProvider:(id)arg1;
- (id)stringFromStreamData:(id)arg1 contentType:(id)arg2;
@end

