//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSDK_GTMOAuth2Keychain : NSObject
{
}

+ (id)defaultKeychain;
+ (id)keychainQueryForService:(id)arg1 account:(id)arg2;
+ (void)setDefaultKeychain:(id)arg1;
- (id)keyForService:(id)arg1 account:(id)arg2;
- (id)keychainQueryForService:(id)arg1 account:(id)arg2;
- (id)passwordForService:(id)arg1 account:(id)arg2 error:(id *)arg3;
- (_Bool)removePasswordForService:(id)arg1 account:(id)arg2 error:(id *)arg3;
- (_Bool)setPassword:(id)arg1 forService:(id)arg2 accessibility:(void *)arg3 account:(id)arg4 error:(id *)arg5;

@end

