//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UINavigationControllerDelegate.h"
#import "UIWebViewDelegate.h"

@class GSDK_GTMOAuth2Authentication, GSDK_GTMOAuth2SignIn, NSArray, NSDictionary, NSMutableDictionary, NSString, NSURL, NSURLRequest, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIView, UIWebView;

@interface GSDK_GTMOAuth2ViewControllerTouch : UIViewController <UINavigationControllerDelegate, UIWebViewDelegate>
{
    UIButton *backButton_;
    UIButton *forwardButton_;
    UIActivityIndicatorView *initialActivityIndicator_;
    UIView *navButtonsView_;
    UIBarButtonItem *rightBarButtonItem_;
    UIWebView *webView_;
    GSDK_GTMOAuth2SignIn *signIn_;
    NSURLRequest *request_;
    id delegate_;
    SEL finishedSelector_;
    id completionBlock_;
    id popViewBlock_;
    NSString *keychainItemName_;
    void *keychainItemAccessibility_;
    NSString *initialHTMLString_;
    int mustShowActivityIndicator_;
    NSURL *browserCookiesURL_;
    id userData_;
    NSMutableDictionary *properties_;
    _Bool isViewShown_;
    _Bool didViewAppear_;
    _Bool hasNotifiedWebViewStartedLoading_;
    _Bool hasCalledFinished_;
    _Bool hasDoneFinalRedirect_;
    _Bool didDismissSelf_;
    unsigned long long savedCookiePolicy_;
    NSArray *systemCookies_;
    NSArray *signInCookies_;
}

+ (id)authForGoogleFromKeychainForName:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3;
+ (id)authForGoogleFromKeychainForName:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3 error:(id *)arg4;
+ (id)authNibBundle;
+ (id)authNibName;
+ (_Bool)authorizeFromKeychainForName:(id)arg1 authentication:(id)arg2 error:(id *)arg3;
+ (id)controllerWithAuthentication:(id)arg1 authorizationURL:(id)arg2 keychainItemName:(id)arg3 completionHandler:(id)arg4;
+ (id)controllerWithAuthentication:(id)arg1 authorizationURL:(id)arg2 keychainItemName:(id)arg3 delegate:(id)arg4 finishedSelector:(SEL)arg5;
+ (id)controllerWithScope:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3 keychainItemName:(id)arg4 completionHandler:(id)arg5;
+ (id)controllerWithScope:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3 keychainItemName:(id)arg4 delegate:(id)arg5 finishedSelector:(SEL)arg6;
+ (_Bool)removeAuthFromKeychainForName:(id)arg1;
+ (void)revokeTokenForGoogleAuthentication:(id)arg1;
+ (_Bool)saveParamsToKeychainForName:(id)arg1 accessibility:(void *)arg2 authentication:(id)arg3 error:(id *)arg4;
+ (_Bool)saveParamsToKeychainForName:(id)arg1 authentication:(id)arg2;
+ (void)setSignInClass:(Class)arg1;
+ (Class)signInClass;
@property(readonly, retain, nonatomic) GSDK_GTMOAuth2Authentication *authentication;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=backButton_;
@property(retain, nonatomic) NSURL *browserCookiesURL; // @synthesize browserCookiesURL=browserCookiesURL_;
- (void)cancelSigningIn;
- (void)dealloc;
@property(retain, nonatomic) UIButton *forwardButton; // @synthesize forwardButton=forwardButton_;
- (id)initWithAuthentication:(id)arg1 authorizationURL:(id)arg2 keychainItemName:(id)arg3 completionHandler:(id)arg4;
- (id)initWithAuthentication:(id)arg1 authorizationURL:(id)arg2 keychainItemName:(id)arg3 delegate:(id)arg4 finishedSelector:(SEL)arg5;
- (id)initWithScope:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3 keychainItemName:(id)arg4 completionHandler:(id)arg5;
- (id)initWithScope:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3 keychainItemName:(id)arg4 delegate:(id)arg5 finishedSelector:(SEL)arg6;
@property(retain, nonatomic) UIActivityIndicatorView *initialActivityIndicator; // @synthesize initialActivityIndicator=initialActivityIndicator_;
@property(copy, nonatomic) NSString *initialHTMLString; // @synthesize initialHTMLString=initialHTMLString_;
- (_Bool)isBeingObscured:(id)arg1;
- (_Bool)isNavigationBarTranslucent;
@property(nonatomic) void *keychainItemAccessibility; // @synthesize keychainItemAccessibility=keychainItemAccessibility_;
@property(copy, nonatomic) NSString *keychainItemName; // @synthesize keychainItemName=keychainItemName_;
- (void)loadView;
- (void)moveWebViewFromUnderNavigationBar;
@property(retain, nonatomic) UIView *navButtonsView; // @synthesize navButtonsView=navButtonsView_;
@property(nonatomic) double networkLossTimeoutInterval;
- (void)notifyWithName:(id)arg1 webView:(id)arg2 kind:(id)arg3;
- (void)popView;
@property(copy, nonatomic) id popViewBlock; // @synthesize popViewBlock=popViewBlock_;
@property(retain, nonatomic) NSDictionary *properties; // @synthesize properties=properties_;
- (id)propertyForKey:(id)arg1;
@property(copy, nonatomic) NSURLRequest *request; // @synthesize request=request_;
@property(retain, nonatomic) UIBarButtonItem *rightBarButtonItem; // @synthesize rightBarButtonItem=rightBarButtonItem_;
- (void)setProperty:(id)arg1 forKey:(id)arg2;
@property(nonatomic) _Bool showsInitialActivityIndicator;
@property(copy, nonatomic) NSArray *signInCookies; // @synthesize signInCookies=signInCookies_;
@property(copy, nonatomic) NSArray *systemCookies; // @synthesize systemCookies=systemCookies_;
- (void)setUpNavigation;
@property(retain, nonatomic) id userData; // @synthesize userData=userData_;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=webView_;
- (_Bool)shouldUseKeychain;
@property(readonly, retain, nonatomic) GSDK_GTMOAuth2SignIn *signIn; // @synthesize signIn=signIn_;
- (void)signIn:(id)arg1 displayRequest:(id)arg2;
- (void)signIn:(id)arg1 finishedWithAuth:(id)arg2 error:(id)arg3;
- (id)swapBrowserCookies:(id)arg1;
- (void)swapInCookies;
- (void)swapOutCookies;
- (id)systemCookieStorage;
- (void)updateUI;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

