//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSInputStream.h"

#import "NSStreamDelegate.h"

@class NSArray, NSString;

@interface GSDK_GTMGatherInputStream : NSInputStream <NSStreamDelegate>
{
    NSArray *_dataArray;
    unsigned long long _arrayIndex;
    long long _dataOffset;
    unsigned long long _streamStatus;
    id <NSStreamDelegate> _delegate;
}

+ (id)streamWithArray:(id)arg1;
- (void).cxx_destruct;
- (long long)absoluteOffset;
- (void)close;
- (id)delegate;
- (_Bool)getBuffer:(char **)arg1 length:(unsigned long long *)arg2;
- (_Bool)hasBytesAvailable;
- (id)initWithArray:(id)arg1;
- (void)open;
- (id)propertyForKey:(id)arg1;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2;
- (void)setAbsoluteOffset:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (_Bool)setProperty:(id)arg1 forKey:(id)arg2;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (id)streamError;
- (unsigned long long)streamStatus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

