//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSInputStream.h"

#import "NSStreamDelegate.h"

@class NSArray, NSString, NSThread;

@interface GSDK_GTMReadMonitorInputStream : NSInputStream <NSStreamDelegate>
{
    NSInputStream *_inputStream;
    NSThread *_thread;
    NSArray *_runLoopModes;
    id _readDelegate;
    SEL _readSelector;
}

+ (void)forwardInvocation:(id)arg1;
+ (id)inputStreamWithStream:(id)arg1;
+ (id)methodSignatureForSelector:(SEL)arg1;
- (void).cxx_destruct;
- (void)close;
- (id)delegate;
- (void)forwardInvocation:(id)arg1;
- (_Bool)getBuffer:(char **)arg1 length:(unsigned long long *)arg2;
- (_Bool)hasBytesAvailable;
- (id)init;
- (id)initWithStream:(id)arg1;
- (void)invokeReadSelectorWithBuffer:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)open;
- (id)propertyForKey:(id)arg1;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
@property __weak id readDelegate; // @synthesize readDelegate=_readDelegate;
@property SEL readSelector; // @synthesize readSelector=_readSelector;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (_Bool)respondsToSelector:(SEL)arg1;
@property(retain) NSArray *runLoopModes; // @synthesize runLoopModes=_runLoopModes;
- (void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2;
- (void)setDelegate:(id)arg1;
- (_Bool)setProperty:(id)arg1 forKey:(id)arg2;
- (id)streamError;
- (unsigned long long)streamStatus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

