//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GSDK_GTMSessionFetcher, NSDate, NSObject<OS_dispatch_queue>, NSOperationQueue, NSURLRequest, NSURLSession;

@protocol GTMSessionFetcherServiceProtocol <NSObject>
@property(retain) NSObject<OS_dispatch_queue> *callbackQueue;
@property(readonly) NSOperationQueue *delegateQueue;
- (void)fetcherDidBeginFetching:(GSDK_GTMSessionFetcher *)arg1;
- (void)fetcherDidCreateSession:(GSDK_GTMSessionFetcher *)arg1;
- (void)fetcherDidStop:(GSDK_GTMSessionFetcher *)arg1;
- (_Bool)fetcherShouldBeginFetching:(GSDK_GTMSessionFetcher *)arg1;
- (GSDK_GTMSessionFetcher *)fetcherWithRequest:(NSURLRequest *)arg1;
- (_Bool)isDelayingFetcher:(GSDK_GTMSessionFetcher *)arg1;
@property _Bool reuseSession;
- (NSURLSession *)session;
- (id <NSURLSessionDelegate>)sessionDelegate;
- (NSURLSession *)sessionForFetcherCreation;
- (NSDate *)stoppedAllFetchersDate;
@end

