//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSArray, NSString, UITextField, UITextView, UIToolbar, UIView;

@interface KeyboardDelegate : NSObject <UITextFieldDelegate, UITextViewDelegate>
{
    UITextView *textView;
    UIToolbar *viewToolbar;
    NSArray *viewToolbarItems;
    UITextField *textField;
    UIToolbar *fieldToolbar;
    NSArray *fieldToolbarItems;
    UIView *inputView;
    UIView *editView;
    struct CGRect _area;
    NSString *initialText;
    long long keyboardType;
    _Bool _multiline;
    _Bool _inputHidden;
    _Bool _active;
    _Bool _done;
    _Bool _canceled;
    _Bool _rotating;
    NSString *text;
    struct CGRect area;
}

+ (void)FinishReorientation;
+ (void)Initialize;
+ (id)Instance;
+ (void)StartReorientation;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) _Bool canceled; // @synthesize canceled=_canceled;
- (struct CreateToolbarResult)createToolbarWithView:(id)arg1;
@property(readonly, nonatomic) _Bool done; // @synthesize done=_done;
@property(retain, nonatomic, getter=getText, setter=setText:) NSString *text; // @synthesize text;
- (void)hide;
- (void)hideUI;
- (id)init;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)positionInput:(struct CGRect)arg1 x:(float)arg2 y:(float)arg3;
@property(readonly, nonatomic, getter=queryArea) struct CGRect area; // @synthesize area;
- (void)setKeyboardParams:(CDStruct_4c437055)arg1;
- (void)setTextInputTraits:(id)arg1 withParam:(CDStruct_4c437055)arg2 withCap:(long long)arg3;
- (void)setTextWorkaround:(id)arg1 text:(id)arg2;
- (void)shouldHideInput:(_Bool)arg1;
- (void)show;
- (void)showUI;
- (void)systemHideKeyboard;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textInputCancel:(id)arg1;
- (void)textInputDone:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)updateInputHidden;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

