//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMMotionActivityManager, NSOperationQueue;

@interface NIAIosActivityManager : NSObject
{
    struct Activity _userActivity;
    CMMotionActivityManager *_activityManager;
    NSOperationQueue *_activityQueue;
    struct IosActivityProvider *_activityProvider;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) struct IosActivityProvider *activityProvider; // @synthesize activityProvider=_activityProvider;
- (void)checkAuthorization:(id)arg1;
- (void)dealloc;
- (void)handleActivityUpdate:(id)arg1;
- (id)init;
- (int)mapConfidenceToInt:(long long)arg1;
- (void)setLocationProvider:(struct IosActivityProvider *)arg1;
- (void)start;
- (void)stop;

@end

