//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (FIFE)
- (id)FIFEArgumentsString;
- (id)FIFELegacyURLWithArgumentsString:(id)arg1;
- (id)FIFEURLRequestingCenteredCropToDimensions:(struct CGSize)arg1;
- (id)FIFEURLRequestingDimensions:(struct CGSize)arg1;
- (id)FIFEURLRequestingExactDimensions:(struct CGSize)arg1;
- (id)FIFEURLRequestingMaxSize:(double)arg1;
- (id)FIFEURLRequestingSmartCropToDimensions:(struct CGSize)arg1;
- (id)FIFEURLRequestingSmartCropToMaxSize:(double)arg1;
- (id)FIFEURLWithArguments:(id)arg1;
- (id)URLByAppendingTrailingSlash;
- (id)URLByRemovingFIFEInfo;
- (_Bool)isFIFEUrl;
- (_Bool)isLegacyFIFEURL;
- (id)legacyFIFEArgumentsString;
- (struct CGSize)maximumFIFEImageSize;
@end

