//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIApplicationDelegate.h"

@class CADisplayLink, DisplayConnection, NSString, UIView, UIViewController, UIWindow, UnityView, UnityViewControllerBase;

@interface UnityAppController : NSObject <UIApplicationDelegate>
{
    UnityView *_unityView;
    CADisplayLink *_displayLink;
    UIWindow *_window;
    UIView *_rootView;
    UIViewController *_rootController;
    UIView *_snapshotView;
    DisplayConnection *_mainDisplay;
    UnityViewControllerBase *_viewControllerForOrientation[5];
    long long _curOrientation;
    id <RenderPluginDelegate> _renderDelegate;
    CADisplayLink *_unityDisplayLink;
    id _quitHandler;
}

- (void).cxx_destruct;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(id)arg3;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (id)init;
@property(readonly, nonatomic) long long interfaceOrientation; // @synthesize interfaceOrientation=_curOrientation;
@property(readonly, copy, nonatomic) DisplayConnection *mainDisplay; // @synthesize mainDisplay=_mainDisplay;
- (void)preStartUnity;
@property(copy, nonatomic) id quitHandler; // @synthesize quitHandler=_quitHandler;
@property(retain, nonatomic) id renderDelegate; // @synthesize renderDelegate=_renderDelegate;
@property(readonly, copy, nonatomic) UIView *rootView; // @synthesize rootView=_rootView;
@property(readonly, copy, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootController;
@property(retain, nonatomic) UIWindow *window;
- (void)shouldAttachRenderDelegate;
- (void)startUnity:(id)arg1;
@property(readonly, copy, nonatomic) CADisplayLink *unityDisplayLink; // @synthesize unityDisplayLink=_unityDisplayLink;
@property(readonly, copy, nonatomic) UnityView *unityView; // @synthesize unityView=_unityView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

