//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface UpsightDynamicConfiguration : NSObject
{
    id <UpsightDynamicConfigurationDelegate> _delegate;
    NSDictionary *_configuration;
}

+ (id)defaultConfiguration;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak id <UpsightDynamicConfigurationDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithConfiguration:(id)arg1;
- (void)updateConfiguration:(id)arg1;
- (void)willUnload;

@end

