//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USActionFactoryInterface.h"
#import "USActionHandlerRegistry.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface USActionFactory : NSObject <USActionFactoryInterface, USActionHandlerRegistry>
{
    NSMutableDictionary *_actionToHandlerMap;
    NSDictionary *_actionToBuilderMap;
}

- (void).cxx_destruct;
- (id)UXMEnumerateBuilder;
@property(readonly) NSDictionary *actionToBuilderMap; // @synthesize actionToBuilderMap=_actionToBuilderMap;
@property(readonly) NSMutableDictionary *actionToHandlerMap; // @synthesize actionToHandlerMap=_actionToHandlerMap;
- (id)actionWithDictionary:(id)arg1 map:(id)arg2;
- (id)associateOnceBuilder;
- (id)buildContentBuilder;
- (id)disposeActionMapBuilder;
- (id)modifyValueBuilder;
- (id)notifyPurchasesBuilder;
- (id)notifyRewardsBuilder;
- (id)notifyUXMValuesSynchronized;
- (id)openInAppStoreBuilder;
- (id)openURLBuilder;
- (id)presentCloseButtonBuilder;
- (id)presentScopedContentBuilder;
- (id)presentScopelessContentBuilder;
- (void)registerHandler:(id)arg1 forActionType:(id)arg2;
- (id)sendEventBuilder;
- (id)sendFormDataBuilder;
- (id)setBundleIDBuilder;
- (id)triggerActionBuilder;
- (id)triggerIfContentAvailableBuilder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

