//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, NSOperationQueue, NSString, NSTimer, USEventBatch, USQueueConfiguration, USRequestAttributeSetBuilder;

@interface USBatcher : NSObject
{
    id <USBatcherDelegate> _delegate;
    NSOperationQueue *_operationQueue;
    USEventBatch *_activeBatch;
    NSMutableSet *_pendingBatches;
    id <USDataSenderInterface> _dataSender;
    NSTimer *_sendTimer;
    NSTimer *_retryTimer;
    NSMutableDictionary *_retryInfos;
    USRequestAttributeSetBuilder *_attributeBuilder;
    NSString *_attributeSetName;
    USQueueConfiguration *_queueConfiguration;
}

- (void).cxx_destruct;
@property(retain, nonatomic) USEventBatch *activeBatch; // @synthesize activeBatch=_activeBatch;
@property(retain, nonatomic) USRequestAttributeSetBuilder *attributeBuilder; // @synthesize attributeBuilder=_attributeBuilder;
@property(retain, nonatomic) NSString *attributeSetName; // @synthesize attributeSetName=_attributeSetName;
@property(retain, nonatomic) id <USDataSenderInterface> dataSender; // @synthesize dataSender=_dataSender;
@property(nonatomic) __weak id <USBatcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dispatchBatch:(id)arg1;
- (void)drain;
- (id)endpointURLForQueueConfiguration:(id)arg1;
- (void)enqueueEvent:(id)arg1;
- (id)init;
- (id)initWithQueueConfiguration:(id)arg1 attributeSetName:(id)arg2 attributeBuilder:(id)arg3 dataSender:(id)arg4 operationQueue:(id)arg5;
- (void)installRetryTimer;
- (void)installSendTimer;
- (void)invalidateSendTimer;
- (void)onRetryTimerDidFire:(id)arg1;
- (void)onSendTimerDidFire:(id)arg1;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) NSMutableSet *pendingBatches; // @synthesize pendingBatches=_pendingBatches;
@property(retain) USQueueConfiguration *queueConfiguration; // @synthesize queueConfiguration=_queueConfiguration;
- (void)removeRetryInfoForBatch:(id)arg1;
- (id)retryInfoForBatch:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *retryInfos; // @synthesize retryInfos=_retryInfos;
@property(retain, nonatomic) NSTimer *retryTimer; // @synthesize retryTimer=_retryTimer;
@property(retain, nonatomic) NSTimer *sendTimer; // @synthesize sendTimer=_sendTimer;
- (_Bool)shouldRetryBatch:(id)arg1 afterError:(id)arg2;

@end

