//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKStoreProductViewControllerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"
#import "USBillboard.h"
#import "USContentUnitViewControllerDelegate.h"

@class NSString, SKStoreProductViewController, USContentUnitViewController;

@interface USContentUnitBillboard : NSObject <USContentUnitViewControllerDelegate, UIViewControllerTransitioningDelegate, SKStoreProductViewControllerDelegate, USBillboard>
{
    _Bool _presenting;
    NSString *_scope;
    id <USBillboardDelegate> _delegate;
    USContentUnitViewController *_viewController;
    id <USContentUnitBillboardDataSource> _dataSource;
    SKStoreProductViewController *_inAppStoreController;
}

+ (id)presentingControllerToScopeMap;
- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)cleanupPresentingControllerToScopeMap;
- (void)contentUnitViewControllerDidDismiss:(id)arg1;
- (void)contentUnitViewControllerWillDismiss:(id)arg1;
@property __weak id <USContentUnitBillboardDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)dealloc;
@property __weak id <USBillboardDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissViewControllerAnimated:(_Bool)arg1;
- (void)executeBlockOnMainQueue:(id)arg1 waitUntilFinished:(_Bool)arg2;
@property(retain) SKStoreProductViewController *inAppStoreController; // @synthesize inAppStoreController=_inAppStoreController;
- (id)initWithScope:(id)arg1;
@property(readonly, getter=isContentReady) _Bool contentReady;
@property(readonly, getter=isPresenting) _Bool presenting; // @synthesize presenting=_presenting;
- (void)onDidEnterBackground:(id)arg1;
- (void)onDidReceivePurchases:(id)arg1;
- (void)onDidReceiveRewards:(id)arg1;
- (_Bool)presentViewController:(id)arg1 animated:(_Bool)arg2;
- (void)presentViewController:(id)arg1 presentingViewController:(id)arg2 animated:(_Bool)arg3 completion:(id)arg4;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)replacePresentedControllerWithStoreUsingITunesIdentifier:(id)arg1 completion:(id)arg2;
- (void)replacePresentedControllerWithViewController:(id)arg1 completion:(id)arg2;
@property(readonly, copy) NSString *scope; // @synthesize scope=_scope;
@property(retain) USContentUnitViewController *viewController; // @synthesize viewController=_viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

