//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSMutableData, NSOperationQueue, NSString, NSURLConnection;

@interface USConnectionInfo : NSObject
{
    NSURLConnection *_connection;
    NSMutableData *_responseData;
    NSOperationQueue *_callbackQueue;
    NSString *_referenceID;
    NSString *_signature;
    NSError *_error;
    id _completionHandler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSOperationQueue *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(copy, nonatomic) id completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void)notifyClientWithCompletionHandler:(id)arg1;
@property(retain, nonatomic) NSString *referenceID; // @synthesize referenceID=_referenceID;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) NSString *signature; // @synthesize signature=_signature;

@end

