//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USBaseAction.h"

@class NSDictionary, NSString;

@interface USConditionalAction : USBaseAction
{
    NSDictionary *_conditionParameters;
    NSString *_thenTrigger;
    NSString *_elseTrigger;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *conditionParameters; // @synthesize conditionParameters=_conditionParameters;
@property(readonly, nonatomic) NSString *elseTrigger; // @synthesize elseTrigger=_elseTrigger;
- (id)initWithParameters:(id)arg1 map:(id)arg2 handler:(id)arg3;
@property(readonly, nonatomic) NSString *thenTrigger; // @synthesize thenTrigger=_thenTrigger;

@end

