//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UpsightDefaultsImpl.h"

@class NSMutableDictionary, NSString;

@interface USDataStoreBasedDefaultsImpl : NSObject <UpsightDefaultsImpl>
{
    NSMutableDictionary *_defaultsMap;
    id <UpsightDataStoreInterface> _dataStore;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
- (id)defaultForKey:(id)arg1;
@property(readonly) NSMutableDictionary *defaultsMap; // @synthesize defaultsMap=_defaultsMap;
- (id)init;
- (id)initWithDataStore:(id)arg1;
- (void)removeAllDefaults;
- (void)removeDefaultForKey:(id)arg1;
- (void)setDefault:(id)arg1 forKey:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

