//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface USEventFactory : NSObject
{
}

+ (id)UXMEnumerateEventWithUXMSchema:(id)arg1 pubData:(id)arg2;
+ (id)analyticsEventWithName:(id)arg1 pubData:(id)arg2;
+ (id)configurationRequestWithPubData:(id)arg1;
+ (id)dataCollectionEventWitDataBundle:(id)arg1 streamID:(id)arg2 pubData:(id)arg3;
+ (id)dynamicEventWithEventDictionary:(id)arg1;
+ (id)inAppPurchaseEventWithIAPInfo:(id)arg1 pubData:(id)arg2;
+ (id)installEventWithPubData:(id)arg1;
+ (id)milestoneEventForScope:(id)arg1 pubData:(id)arg2;
+ (id)monetizationEventWithInfo:(id)arg1 pubData:(id)arg2;
+ (id)pushReceivedEventWithMessageID:(id)arg1 campaignID:(id)arg2 pubData:(id)arg3;
+ (id)pushRegistrationEventWithToken:(id)arg1 pubData:(id)arg2;
+ (id)pushUnregistrationEventWithPubData:(id)arg1;
+ (id)sessionPauseEventWithPubData:(id)arg1;
+ (id)sessionResumeEventWithPubData:(id)arg1;
+ (id)sessionStartEventWithPubData:(id)arg1;
+ (id)sharedFactory;
+ (id)unrenderedContentEventWithContentID:(id)arg1 campaignID:(id)arg2 scope:(id)arg3 pubData:(id)arg4;
- (id)buildEventWithInitializer:(id)arg1 attributeSetName:(id)arg2 pubData:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)eventParametersWithAttributeSetName:(id)arg1 pubData:(id)arg2;
- (void)extendEventWithAssociatedData:(id)arg1;

@end

