//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface USMutableNumber : NSObject
{
    NSNumber *_numberValue;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithInteger:(unsigned long long)arg1;
@property(nonatomic) long long integerValue;
@property(retain, nonatomic) NSNumber *numberValue; // @synthesize numberValue=_numberValue;

@end

