//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USBaseAction.h"

@class NSURL;

@interface USOpenURLAction : USBaseAction
{
    NSURL *_URL;
}

+ (id)type;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (id)initWithParameters:(id)arg1 map:(id)arg2 handler:(id)arg3;

@end

