//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USPurchase.h"

@class NSString;

@interface USPurchaseImpl : NSObject <USPurchase>
{
    NSString *_productIdentifier;
    unsigned long long _quantity;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithDictionary:(id)arg1;
@property(readonly, nonatomic) NSString *productIdentifier; // @synthesize productIdentifier=_productIdentifier;
@property(readonly, nonatomic) unsigned long long quantity; // @synthesize quantity=_quantity;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

