//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USBaseAction.h"

@class NSString;

@interface USSendFormDataAction : USBaseAction
{
    NSString *_dataKey;
    NSString *_streamID;
}

+ (id)type;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *dataKey; // @synthesize dataKey=_dataKey;
- (id)initWithParameters:(id)arg1 map:(id)arg2 handler:(id)arg3;
@property(readonly, nonatomic) NSString *streamID; // @synthesize streamID=_streamID;

@end

