//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface USStateDefinition : NSObject
{
    id _enterBlock;
    id _executeBlock;
    id _exitBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) id enterBlock; // @synthesize enterBlock=_enterBlock;
@property(copy, nonatomic) id executeBlock; // @synthesize executeBlock=_executeBlock;
@property(copy, nonatomic) id exitBlock; // @synthesize exitBlock=_exitBlock;

@end

