//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface USUXMModifyValueActionHandler : NSObject
{
    id <UpsightDataStoreInterface> _dataStore;
    id <USActionHandlerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
@property(nonatomic) __weak id <USActionHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithDataStore:(id)arg1;
@property(readonly, nonatomic) id modifyValueActionHandler;

@end

