//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface USUXMSchema : NSObject
{
    NSArray *_tags;
    NSArray *_arrayRepresentation;
    NSDictionary *_variablesForTags;
    NSString *_schemaHash;
}

+ (id)arrayRepresentation;
+ (id)schemaForTag:(id)arg1;
+ (id)schemaHash;
+ (id)sharedSchema;
+ (id)tags;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *arrayRepresentation; // @synthesize arrayRepresentation=_arrayRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)loadUXMVariables;
- (id)schemaFilePath;
- (id)schemaForTag:(id)arg1;
@property(retain, nonatomic) NSString *schemaHash; // @synthesize schemaHash=_schemaHash;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(retain, nonatomic) NSDictionary *variablesForTags; // @synthesize variablesForTags=_variablesForTags;

@end

