//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetReader, AVAssetReaderTrackOutput, AVPlayer, AVPlayerItem;

@interface VideoPlayer : NSObject
{
    id <VideoPlayerDelegate> delegate;
    AVPlayerItem *_playerItem;
    AVPlayer *_player;
    AVAssetReader *_reader;
    AVAssetReaderTrackOutput *_videoOut;
    struct opaqueCMSampleBuffer *_cmSampleBuffer;
    struct CMVideoSampling _videoSampling;
    CDStruct_1b6d18a9 _duration;
    CDStruct_1b6d18a9 _curTime;
    CDStruct_1b6d18a9 _curFrameTimestamp;
    CDStruct_1b6d18a9 _lastFrameTimestamp;
    struct CGSize _videoSize;
    _Bool _playerReady;
    _Bool _assetReady;
    _Bool _itemReady;
}

+ (_Bool)CanPlayToTexture:(id)arg1;
+ (_Bool)CheckScalingModeAspectFill:(struct CGSize)arg1 screenSize:(struct CGSize)arg2;
- (void).cxx_destruct;
- (_Bool)_playWithPrepareBlock:(id)arg1;
- (void)audioRouteChanged:(id)arg1;
- (void)cleanupAssetReader;
- (void)cleanupCVTextureCache;
- (void)cleanupPlayer;
- (long long)curFrameTexture;
@property(retain, nonatomic) id delegate; // @synthesize delegate;
- (CDStruct_1b6d18a9)duration;
- (float)durationSeconds;
- (id)init;
- (_Bool)isPlaying;
- (_Bool)loadVideo:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)pause;
- (_Bool)playToTexture;
- (_Bool)playToView:(id)arg1;
- (_Bool)playVideoPlayer;
@property(readonly, nonatomic) AVPlayer *player; // @synthesize player=_player;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)prepareAsset:(id)arg1 withKeys:(id)arg2;
- (_Bool)prepareReader;
- (_Bool)readyToPlay;
- (void)reportError:(id)arg1 category:(const char *)arg2;
- (void)reportErrorWithString:(const char *)arg1 category:(const char *)arg2;
- (void)resume;
- (void)rewind;
- (void)seekTo:(float)arg1;
- (void)seekToTimestamp:(CDStruct_1b6d18a9)arg1;
- (_Bool)setAudioVolume:(float)arg1;
- (void)unloadPlayer;
- (struct CGSize)videoSize;

@end

